### ISSUE TITLE
tudou视频下载错误

### ISSUE THREAD

**Issue by friskfly** [iambus/youku-lixian#21]
貌似提取视频title的正则失效了

D:\下载\iambus-youku-lixian-7720b95>python video_lixian.py http://www.tudou.com/programs/view/SGfYUr
tzMe8/?resourceId=101048554_06_02_99
Traceback (most recent call last):
  File "video_lixian.py", line 50, in <module>
    main()
  File "video_lixian.py", line 47, in main
    script_main('video_lixian', any_download, any_download_playlist)
  File "D:\下载\iambus-youku-lixian-7720b95\common.py", line 261, in script_main
    download(url)
  File "video_lixian.py", line 40, in any_download
    m.download(url)
  File "D:\下载\iambus-youku-lixian-7720b95\tudou.py", line 31, in tudou_download
    assert title
AssertionError

**Comment by lilydjwg** [comment]
我也遇到了这个问题。

**Comment by soimort** [comment]
问题同上。

$ python2 ./video_lixian.py "http://www.tudou.com/programs/view/OeZFTD_Fyso"
Traceback (most recent call last):
  File "./video_lixian.py", line 57, in <module>
    main()
  File "./video_lixian.py", line 54, in main
    script_main('video_lixian', any_download, any_download_playlist)
  File "/home/soimort/Source/youku-lixian/common.py", line 264, in script_main
    download(url)
  File "./video_lixian.py", line 47, in any_download
    m.download(url)
  File "/home/soimort/Source/youku-lixian/tudou.py", line 31, in tudou_download
    assert title
AssertionError
