### ISSUE TITLE
Error with Youku

### ISSUE THREAD

**Issue by juliecheng** [iambus/youku-lixian#29]
C:\Users\asdf\youku-lixian>python youku.py --playlist http://www.youku.com/play
list_show/id_4248711.html
Downloading 1 of 22 videos...
Downloading ----22(---).flv ...
Traceback (most recent call last):
  File "youku.py", line 169, in <module>
    main()
  File "youku.py", line 166, in main
    script_main('youku', youku_download, youku_download_playlist)
  File "C:\Users\asdf\youku-lixian\common.py", line 272, in script_main
    download_playlist(url)
  File "youku.py", line 160, in youku_download_playlist
    youku_download(id)
  File "youku.py", line 111, in youku_download
    youku_download_by_id(id2, title, output_dir)
  File "youku.py", line 99, in youku_download_by_id
    download_urls(urls, title, file_type_of_url(urls[0]), total_size, output_dir
)
  File "C:\Users\asdf\youku-lixian\common.py", line 212, in download_urls
    url_save(url, filepath, bar, refer=refer)
  File "C:\Users\asdf\youku-lixian\common.py", line 75, in url_save
    response = urllib2.urlopen(request)
  File "c:\python27\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "c:\python27\lib\urllib2.py", line 406, in open
    response = meth(req, response)
  File "c:\python27\lib\urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python27\lib\urllib2.py", line 444, in error
    return self._call_chain(_args)
  File "c:\python27\lib\urllib2.py", line 378, in _call_chain
    result = func(_args)
  File "c:\python27\lib\urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

是不是因為我在美國?

**Comment by iambus** [comment]
我这边下载没问题。你从网页能正常观看吗？

**Comment by juliecheng** [comment]
我从 google chrome 是可以看，但是那是因为我用modheader更改IP地址。 谢谢！

**Comment by iambus** [comment]
如果不改没法看，那下载失败是正常的。

**Comment by mozbugbox** [comment]
Python 的 urllib2 内建 proxy 支持，只要设定 http_proxy 环境变量就可以。通过国内 proxy 可以转换 ip 。
