### ISSUE TITLE
搜狐视频的无法下载了

### ISSUE THREAD

**Issue by leeight** [iambus/youku-lixian#40]
http://tv.sohu.com/20110923/n320325529.shtml

Traceback (most recent call last):
  File "sohu.py", line 36, in <module>
    main()
  File "sohu.py", line 33, in main
    script_main('sohu', sohu_download)
  File "/home/pi/local/youku-lixian/common.py", line 285, in script_main
    download(url, merge=merge)
  File "sohu.py", line 25, in sohu_download
    urls.append(real_url(host, prot, file, new))
  File "sohu.py", line 9, in real_url
    start, _, host, key, _, _ = get_html(url).split('|')
  File "/home/pi/local/youku-lixian/common.py", line 56, in get_html
    content = get_response(url).data
  File "/home/pi/local/youku-lixian/common.py", line 46, in get_response
    response = urllib2.urlopen(url)
  File "/usr/lib/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 601: Internal Server Error

**Comment by iambus** [comment]
我这边可以正常下载……

**Comment by wz520** [comment]
我也没法下载，和LZ一样也是 HTTP Error 601

E:\youku-lixian\iambus-youku-lixian-8058707>sohu http://tv.sohu.com/20110923/n320325529.shtml
Traceback (most recent call last):
  File "E:\youku-lixian\iambus-youku-lixian-8058707\sohu.py", line 36, in <module>
    main()
  File "E:\youku-lixian\iambus-youku-lixian-8058707\sohu.py", line 33, in main
    script_main('sohu', sohu_download)
  File "E:\youku-lixian\iambus-youku-lixian-8058707\common.py", line 291, in script_main
    download(url, merge=merge)
  File "E:\youku-lixian\iambus-youku-lixian-8058707\sohu.py", line 25, in sohu_download
    urls.append(real_url(host, prot, file, new))
  File "E:\youku-lixian\iambus-youku-lixian-8058707\sohu.py", line 9, in real_url
    start, _, host, key, _, _ = get_html(url).split('|')
  File "E:\youku-lixian\iambus-youku-lixian-8058707\common.py", line 56, in get_html
    content = get_response(url).data
  File "E:\youku-lixian\iambus-youku-lixian-8058707\common.py", line 46, in get_response
    response = urllib2.urlopen(url)
  File "D:\Python27\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "D:\Python27\lib\urllib2.py", line 400, in open
    response = meth(req, response)
  File "D:\Python27\lib\urllib2.py", line 513, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Python27\lib\urllib2.py", line 438, in error
    return self._call_chain(_args)
  File "D:\Python27\lib\urllib2.py", line 372, in _call_chain
    result = func(_args)
  File "D:\Python27\lib\urllib2.py", line 521, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 601: Internal Server Error

**Comment by iambus** [comment]
我还是可以下载……
不知道是临时的问题，还是总这样。你明天再试试吧。
也可以自己在sohu.py第九行前面把url打出来，然后贴下看下。

**Comment by wz520** [comment]
现在下午4点多，还是不行。
我在第8行和第9行之间加了
print url
输出的 url 是这样的：
http://220.181.61.229/?prot=2&file=http://data.vod.itc.cn/stream/20111009/336166-435573.mp4&new=

**Comment by iambus** [comment]
在sohu_download里，把vid和data都打出来吧。

**Comment by wz520** [comment]
在 data = data['data'] 前插入
print 'vid='
print vid
print 'data='
print data

输出

vid=
435573
data=
{u'preload': 0, u'sp': 1024, u'isNewsLogo': 0, u'pid': 1005271, u'areaId': 10, u'caname': u'\u7535\u89c6\u5267', u'cmscat': u'251366993;267906517;274664402;319214481;320325529', u'vt': 1, u'year': 2011, u'scap': [{u'cpath': u'http://tv.sohu.com/upload/srt/1005271_chs_31d03ca7-aa05-4828-973e-e27574c37aab.srt', u'ver': 1}], u'isdl': 0, u'id': 435573, u'pL': 30, u'ct': 42, u'fee': 0, u'catcode': u'101107;101111;101113', u'prot': 2, u'fms': 1, u'data': {u'ch': u'stream', u'xlClipsBytes': [0], u'totalBlocks': 1, u'totalBytes': 78419915, u'height': 352, u'num': 1, u'subName': u'', u'superVid': 435575, u'tvName': u'\u751f\u6d3b\u5927\u7206\u70b8\u7b2c5\u5b63\u7b2c1\u96c6', u'norVid': 435574, u'highVid': 435573, u'ipLimit': 1, u'relativeId': 435574, u'width': 640, u'version': 1, u'xlClipsUrl': None, u'fps': 25, u'eT': 0, u'eP': None, u'adpo': None, u'sT': 0, u'coverImg': u'http://photocdn.sohu.com/20110923/vrs336166.jpg', u'clipsURL': [u'http://data.vod.itc.cn/stream/20111009/336166-435573.mp4'], u'clipsBytes': [78419915], u'oriVid': 0, u'su': [u''], u'clipsDuration': [1292], u'xlClipsDuration': [0], u'totalDuration': 1292.0}, u'tn': 5, u'preview': 2, u'nt': 1, u'company': u'', u'status':
1, u'play': 1, u'p2pflag': 1200, u'fnor': 0, u'ispv': 0, u'uS': -1, u'hcap': 1,
u'reserveIp': u'61.135.183.46;115.25.217.132', u'systype': 0, u'holiday': 0, u'tv_application_time': u'2011-09-23 11:55:00', u'keyword': u'\u751f\u6d3b\u5927\u7206\u70b8\u7b2c5\u5b63\u7b2c1\u96c6', u'url': u'http://tv.sohu.com/20110923/n320325529.shtml', u'age': u'5\u5c81\u4ee5\u4e0b', u'isp2p': 0, u'caid': 2, u'plcatid': 2, u'allot': u'220.181.61.229', u'act': u'', u'oriType': -1, u'mainActorId': u'25501;32379;-1'}

**Comment by iambus** [comment]
和我这边拿到的结果不一样。有一个u'su': [u'']的内容是空的。原因搞不清楚了。我这边重现不出来这个现象，目前也没什么办法。

**Comment by fwolf** [comment]
这个问题又出现了，前一段时间下载 TBBT 第1,2 季时还是好好的：

```
$ ./you-get -V
You-Get 0.3.21-6f77174, a video downloader.
```

下载时输出了 url ：

```
$ ./you-get -i http://tv.sohu.com/20101008/n275478077.shtml
http://tv.sohu.com/20101008/n275478077.shtml
http://220.181.61.229/?prot=2&file=http://data.vod.itc.cn/stream/20121203/91379-888477-99c88242-ca00-4ea9-bde6-840bb9b34462.mp4&new=
Traceback (most recent call last):
  File "./you-get", line 10, in <module>
    main()
  File "/home/fwolf/dev/you-get/src/you_get/downloader/__main__.py", line 81, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/home/fwolf/dev/you-get/src/you_get/common.py", line 820, in script_main
    download_main(download, download_playlist, args, playlist, output_dir, merge, info_only)
  File "/home/fwolf/dev/you-get/src/you_get/common.py", line 730, in download_main
    download(url, output_dir = output_dir, merge = merge, info_only = info_only)
  File "/home/fwolf/dev/you-get/src/you_get/downloader/__main__.py", line 74, in any_download
    m.download(url, output_dir = output_dir, merge = merge, info_only = info_only)
  File "/home/fwolf/dev/you-get/src/you_get/downloader/sohu.py", line 32, in sohu_download
    urls.append(real_url(host, prot, file, new))
  File "/home/fwolf/dev/you-get/src/you_get/downloader/sohu.py", line 11, in real_url
    start, _, host, key = get_html(url).split('|')[:4]
  File "/home/fwolf/dev/you-get/src/you_get/common.py", line 169, in get_html
    content = get_response(url, faker).data
  File "/home/fwolf/dev/you-get/src/you_get/common.py", line 156, in get_response
    response = request.urlopen(url)
  File "/usr/lib/python3.3/urllib/request.py", line 156, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.3/urllib/request.py", line 475, in open
    response = meth(req, response)
  File "/usr/lib/python3.3/urllib/request.py", line 587, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.3/urllib/request.py", line 513, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.3/urllib/request.py", line 447, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.3/urllib/request.py", line 595, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 601: Internal Server Error
```

其中的 http://220.181.61.229/?prot=2&file=http://data.vod.itc.cn/stream/20121203/91379-888477-99c88242-ca00-4ea9-bde6-840bb9b34462.mp4&new= 这个链接手工下载也是 601 错误， http://data.vod.itc.cn/stream/20121203/91379-888477-99c88242-ca00-4ea9-bde6-840bb9b34462.mp4 也是 601 错误：

```
$ curl -I data.vod.itc.cn
HTTP/1.1 601 Internal Server Error
Server: nginx
Date: Sun, 08 Sep 2013 09:21:28 GMT
Content-Length: 0
Connection: close
```
