### ISSUE TITLE
Acfun下载失效

### ISSUE THREAD

**Issue by soimort** [iambus/youku-lixian#43]
``` sh
➜  youku-lixian git:(master) python2 acfun.py http://www.acfun.tv/v/ac432142
Traceback (most recent call last):
  File "acfun.py", line 57, in <module>
    main()
  File "acfun.py", line 54, in main
    script_main('acfun', acfun_download)
  File "/home/soimort/Source/youku-lixian/common.py", line 287, in script_main
    download(url, merge=merge)
  File "acfun.py", line 41, in acfun_download
    assert title
AssertionError
```

**Comment by soimort** [comment]
某些视频用的是小写的`[video]`
http://www.acfun.tv/v/ac432858
http://www.acfun.tv/v/ac433021

还有这个视频貌似是直接引用了http://v.iask.com/v_play.php? 的id…………
http://www.acfun.tv/v/ac89046
