### ISSUE TITLE
我能单纯地报告一个问题吗

### ISSUE THREAD

**Issue by wuyexiong** [iambus/youku-lixian#64]
下载优酷毒战的时候遇到的错误

```
python youku.py http://v.youku.com/v_show/id_XNTU0MzY5OTY0.html
Downloading 毒战.flv ...
 14% [=====-                                  ] 4/32Traceback (most recent call last):
  File "youku.py", line 202, in <module>
    main()
  File "youku.py", line 199, in main
    script_main('youku', youku_download, youku_download_playlist)
  File "/Users/wuyexiong/Dev/soft/net/youku-lixian/common.py", line 287, in script_main
    download(url, merge=merge)
  File "youku.py", line 135, in youku_download
    youku_download_by_id(id2, title, output_dir, merge=merge)
  File "youku.py", line 128, in youku_download_by_id
    download_urls(urls, title, file_type_of_url(urls[0]), total_size, output_dir, merge=merge)
  File "/Users/wuyexiong/Dev/soft/net/youku-lixian/common.py", line 226, in download_urls
    url_save(url, filepath, bar, refer=refer)
  File "/Users/wuyexiong/Dev/soft/net/youku-lixian/common.py", line 75, in url_save
    response = urllib2.urlopen(request)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 400, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 513, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 438, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 372, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 521, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by graycarl** [comment]
貌似是因为这是付费视频。。。
