### ISSUE TITLE
原因不明，貌似不支持格式？

### ISSUE THREAD

**Issue by allanruin** [iambus/youku-lixian#65]
在家，本来打算给家里人下载个舞蹈视屏的，发觉不行了。。记得以前很好用的。
测试地址为：
http://www.56.com/u36/v_NzQzMzU0NzM.html

```
Traceback (most recent call last):
  File "F:\TDDOWNLOAD\youku-lixian-master\w56.py", line 34, in <module>
    main()
  File "F:\TDDOWNLOAD\youku-lixian-master\w56.py", line 31, in main
    script_main('w56', w56_download)
  File "F:\TDDOWNLOAD\youku-lixian-master\common.py", line 287, in script_main
    download(url, merge=merge)
  File "F:\TDDOWNLOAD\youku-lixian-master\w56.py", line 25, in w56_download
    w56_download_by_id(id, merge=merge)
  File "F:\TDDOWNLOAD\youku-lixian-master\w56.py", line 20, in w56_download_by_i
d
    assert ext in ('flv', 'mp4')
AssertionError
```

**Comment by zqfan** [comment]
从chrome插件解析的地址来看
http://222.186.63.40/fcs86.56.com/flvdownload/29/24/134819497651hd.flv?t=y5vvujbnu694iySAi7-skg&r=80167&e=1374129903&v=1&s=1&m=s
格式似乎是flv的

**Comment by zqfan** [comment]
http://f3.r.56.com/f3.c86.56.com/flvdownload/29/24/134819497651hd.flv?v=1&t=BZDEWUoBCRAqFK3v9_Hu-w&r=7284&e=1374130821
这个是w56.py获得的地址，w56认为ext是flv?v=1&t=BZDEWUoBCRAqFK3v9_Hu-w&r=7284&e=1374130821，这引发了断言

**Comment by iambus** [comment]
不好意思，很长时间没有维护这个了。主要问题还是我自己除了偶尔用点youku，其他的都不看。据说现在大多数站点都不能下载了……争取一个月内找时间都过一边。
