### ISSUE TITLE
Please, add atom udta for mp4_join.py

### ISSUE THREAD

**Issue by RomanEmelyanov** [iambus/youku-lixian#82]
$./mp4_join.py --output target.mp4 1.mp4 2.mp4
Joining 1.mp4, 2.mp4 into target.mp4
Traceback (most recent call last):
  File "./mp4_join.py", line 909, in <module>
    main()
  File "./mp4_join.py", line 906, in main
    concat_mp4s(args, output)
  File "./mp4_join.py", line 878, in concat_mp4s
    merge_mp4s(mp4s, output)
  File "./mp4_join.py", line 840, in merge_mp4s
    mp4s = map(read_mp4, ins)
  File "./mp4_join.py", line 684, in read_mp4
    atoms = parse_atoms(stream)
  File "./mp4_join.py", line 676, in parse_atoms
    atom = read_atom(stream)
  File "./mp4_join.py", line 667, in read_atom
    return atom_readers[type](stream, size, left, type)
  File "./mp4_join.py", line 569, in read_composite_atom
    atom = read_atom(stream)
  File "./mp4_join.py", line 668, in read_atom
    raise NotImplementedError('%s: %d' % (type, left))
NotImplementedError: udta: 746
$

**Comment by sandyUni** [comment]
我知道了，这个网页上的东西不存在

**Comment by iambus** [comment]
Where did your 1.mp4 and 2.mp4 come from?

**Comment by RomanEmelyanov** [comment]
I'm download it from Youtube, for example this two video have udta atom:
http://ytapi.com/api/9bZkp7q19f0/direct/18/
http://ytapi.com/api/XSGBVzeBUbk/direct/18/

Code added:
    'pasp': read_raw,
-   'udta': read_composite_atom,
-   'meta': read_raw,
  'mdat': read_mdat,
  After this have another problem:
  #############################################################
  Traceback (most recent call last):
  File "./mp4_join.py", line 929, in <module>
    main()
  File "./mp4_join.py", line 926, in main
    concat_mp4s(args, output)
  File "./mp4_join.py", line 898, in concat_mp4s
    merge_mp4s(mp4s, output)
  File "./mp4_join.py", line 863, in merge_mp4s
    moov = merge_moov(moovs, mdats)
  File "./mp4_join.py", line 792, in merge_moov
    stts0 = merge_stts(x.get('mdia', 'minf', 'stbl', 'stts').body[1] for x in trak0s)
  File "./mp4_join.py", line 722, in merge_stts
    assert len(set(durations)) == 1, 'not all durations equal'
  AssertionError: not all durations equal
  ##################################################################

Any ideas?
